/* Global/App */
export const FETCH_START = 'FETCH_START'
export const FETCH_END = 'FETCH_END'

/* Article */
export const FETCH_ARTICLE_DATA = 'FETCH_ARTICLE_DATA'
export const UPDATE_ARTICLE_DATA = 'UPDATE_ARTICLE_DATA'
export const FETCH_ARTICLE_CONTENT = 'FETCH_ARTICLE_CONTENT'
export const UPDATE_ARTICLE_CONTENT = 'UPDATE_ARTICLE_CONTENT'
